name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secret_reveal_test:
    name: "secret reveal test"
    runs-on: ubuntu-latest
    steps:
      - name: try echo secret
        run: 'echo "secret: ${{ secrets.MY_SECRET }}"'
      - name: write secret to file and cat
        run: |
          echo "${{ secrets.MY_SECRET }}" > secret.txt
          cat secret.txt
      - name: try expose secret as base64
        run: 'echo "secret: ${{ secrets.MY_SECRET }}" | base64'

  # This workflow contains a single job called "test"
  test:
    name: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables that are available to all jobs and steps in this workflow
    env:
      POSTGRES_DSN: postgres://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable

    # Services are Docker containers that are run during a job
    services:
      # Start the postgres database
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      # Setting up Go in the runner
      - name: setup go
        uses: actions/setup-go@v3

      # Cache Go build cache and modcache
      - name: cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Runs Go tests
      - name: test
        run: go test ./...

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
